# Copyright (c) 2022, Linaro
# SPDX-License-Identifier: Apache-2.0

name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: step
      
      - name: Initialize
        working-directory: step
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt
          west zephyr-export
      
      - name: Build firmware
        working-directory: step
        run: |
          west build -b mps2_an521 samples/shell
      
      - name: Test
        working-directory: step
        run: |
          ../zephyr/scripts/twister --inline-logs -p qemu_cortex_m3 -T tests  -v
