# Copyright (c) 2022, Linaro
# SPDX-License-Identifier: Apache-2.0

name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: step
      
      - name: Initialize
        working-directory: step
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt
          west zephyr-export
      
      - name: Build samples
        working-directory: step
        run: |
          west build -p always -b nucleo_g474re samples/foc_controller
          rm -rf build
          west build -p always -b b_u585i_iot02a samples/fusion_imu
          rm -rf build
          west build -p always -b mps2_an521 samples/shell
          rm -rf build
          west build -p always -b mps2_an521 samples/simple_subscription
          rm -rf build
          west build -p always -b mps2_an521 samples/throughput
      
      - name: Test
        working-directory: step
        run: |
          ../zephyr/scripts/twister --inline-logs -p mps2_an521 -T tests  -v
